# `version` is now deprecated
# https://docs.docker.com/compose/compose-file/#version-top-level-element

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    env_file:
      - ./app/.env
    ports:
      - 3000:3000
    depends_on:
      - django
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    restart: always

  django:
    container_name: django
    build:
      context: ./apiserver
      dockerfile: ./compose/local/Dockerfile
    image: django
    depends_on:
      - postgres
      - sandbox
    # volumes:
    #   - .:/apiserver:z
    env_file:
      - ./apiserver/.envs/.local/.django
      - ./apiserver/.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: ./apiserver
      dockerfile: ./compose/production/postgres/Dockerfile
    image: django_postgres
    container_name: django_postgres
    env_file:
      - ./apiserver/.envs/.local/.postgres

  sandbox:
    build: 
      context: ./apiserver
      dockerfile: ./compose/production/sandbox/Dockerfile
    image: sandbox
    container_name: sandbox


networks:
  my_network:
    external: true